---
title: "Final project draft"
author: "Daisy Fang"
date: "2/16/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
library(tidyverse)
```

```{r load-data}
springfield <- readxl::read_excel("Springfield.xlsx")
```

```{r anonymize-data}
# anonymize client
pallets <- springfield %>% 
  filter(cust_code == 550) %>% 
  select(-cust_name, -cust_code, -phy_key, -product_key, -facilityid) %>% 
  mutate(item_desc = str_remove(item_desc, "BE "),
         item_desc = str_replace(item_desc, " BE ", " "),
         item_desc = str_remove(item_desc, "BEF "))

write_csv(pallets, "pallets.csv")
```

```{r write-data}
all_pallets <- pallets %>% 
  select(-c("item_code", "lot_key", "b_date", "julian_date", "code_date", "location_in", "location_per_mast", "status_per_mast", "date_in_scan", "batch_in", "earliest_date_scan", "latest_date_scan", "location_out", "batch_out", "pallet_height", "room_in", "room_out", "room_mast", "room_any", "days_duration", "time_to_beg_refdate", "time_to_refdate", "pct_in_period"))

write_csv(all_pallets, "all_pallets.csv")
```

